# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KindleSend < Formula
  desc ""
  homepage ""
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nikhil1raghav/kindle-send/releases/download/1.0.3/kindle-send_1.0.3_darwin_amd64.tar.gz"
      sha256 "1fadd3fe5a2712a13eb010f37858816d06a95e534caf1f8fd2820d1c5879023b"

      def install
        bin.install "kindle-send"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nikhil1raghav/kindle-send/releases/download/1.0.3/kindle-send_1.0.3_darwin_arm64.tar.gz"
      sha256 "a5a4f5423cde8fb8cf777b6493ee4f6ae119172955e1c6fa45a4f96154d228e7"

      def install
        bin.install "kindle-send"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikhil1raghav/kindle-send/releases/download/1.0.3/kindle-send_1.0.3_linux_arm64.tar.gz"
      sha256 "6895270aadedc8938adb80a1b978f391c68b7d7a10e90d3f472f5a0b860b94e1"

      def install
        bin.install "kindle-send"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nikhil1raghav/kindle-send/releases/download/1.0.3/kindle-send_1.0.3_linux_amd64.tar.gz"
      sha256 "5f14ca0db5d432a64d6d54de601dc6ee975ef260ffedd5359951aed752817ccb"

      def install
        bin.install "kindle-send"
      end
    end
  end
end
