# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KindleSend < Formula
  desc ""
  homepage ""
  version "2.0.0-rc-1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nikhil1raghav/kindle-send/releases/download/v2.0.0-rc-1/kindle-send_2.0.0-rc-1_darwin_arm64.tar.gz"
      sha256 "5d62bb30b854f10055b195743b7977bb8f8953def9268132c727d1762b982941"

      def install
        bin.install "kindle-send"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nikhil1raghav/kindle-send/releases/download/v2.0.0-rc-1/kindle-send_2.0.0-rc-1_darwin_amd64.tar.gz"
      sha256 "d2cda11795b6069eee552e7de83263fd6ec536034c854d365a4faad356ee1af0"

      def install
        bin.install "kindle-send"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikhil1raghav/kindle-send/releases/download/v2.0.0-rc-1/kindle-send_2.0.0-rc-1_linux_arm64.tar.gz"
      sha256 "41d4dd0238d9ff8c9ea523bb4f7f66b561b11174f484306b210a900955dbcadf"

      def install
        bin.install "kindle-send"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nikhil1raghav/kindle-send/releases/download/v2.0.0-rc-1/kindle-send_2.0.0-rc-1_linux_amd64.tar.gz"
      sha256 "4cd67a62c0df014c23e13e84e1bb8fa378876f5b3828330488b60d87543abf14"

      def install
        bin.install "kindle-send"
      end
    end
  end
end
